# Assignment Day 3 Homework Solution
- Data Science 101 Course
- Name- Prakash Mandekar
- Mail Id - prakashmandekar8@gmail.com

### Questions 1:
- Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np 
  
# Printing all numbers from 2 to 50 in steps of 3 
print(np.arange(2, 50, 3)) 

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Questions 2:
- Accept two lists of 5 elements each from the user.
- Convert them to numpy arrays. Concatenate these arrays and print it. 
- Also sort these arrays and print it.

In [19]:
import numpy 
First_list = int(input("Enter the size of list "))
print("\n")
numList_1 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:First_list]
print("First List: ", numList_1)
print("\n")
Second_list = int(input("Enter the size of list "))
print("\n")
numList_2 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:Second_list]
print("Second List: ", numList_2)
print("\n")
Array_1 = numpy.array(numList_1)
Array_2 = numpy.array(numList_2)

print("Array1 as Numpy_Array ",Array_1)
print("Array2 as Numpy_Array ",Array_2)
print("\n")

Concatenated_array = numpy.concatenate((Array_1, Array_2), axis=0)
print("Concatenated array ", Concatenated_array)
print("\n")
Concatenated_array.sort()
print("Sorted Array ", Concatenated_array)


Enter the size of list 5


Enter the list numbers separated by space 52 41 5 69 95 
First List:  [52, 41, 5, 69, 95]


Enter the size of list 5


Enter the list numbers separated by space 112 47 6 32 95
Second List:  [112, 47, 6, 32, 95]


Array1 as Numpy_Array  [52 41  5 69 95]
Array2 as Numpy_Array  [112  47   6  32  95]


Concatenated array  [ 52  41   5  69  95 112  47   6  32  95]


Sorted Array  [  5   6  32  41  47  52  69  95  95 112]


### Questions 3:
- Write a code snippet to find the dimensions of a ndarray and its size.

In [22]:
# Create a 2D Numpy array list of list
arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print('2D Numpy Array')
print(arr2D)
print("\n")
# get number of rows in 2D numpy array
numOfRows = np.size(arr2D, 0)
# get number of columns in 2D numpy array
numOfColumns = np.size(arr2D, 1)
print('Number of Rows : ', numOfRows)
print('Number of Columns : ', numOfColumns)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


Number of Rows :  3
Number of Columns :  4


### Questions 4:

- How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
- Hint: np.newaxis, np.expand_dims

In [25]:
# create 1D numpy array from a list
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
print("\n")

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print("2D Array ")
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


2D Array 
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Questions 5:
- Consider two square numpy arrays. Stack them vertically and horizontally.
- Hint: Use vstack(), hstack()

In [26]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


### Questions 6:
- How to get unique items and counts of unique items?

In [30]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
      
# driver code 
list1 = [10, 20, 10, 30, 40, 40] 
print("The unique values from 1st list is") 
unique(list1) 
  
# converting our list to set 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
